### ISSUE TITLE
?debugClientLibs=true breaks functionality on publish instance

### ISSUE THREAD

**Issue by geekyrudh** [mickleroy/aem-sass-compiler#9] opened 2017-09-20 11:19 UTC
This issue only occurs in the publish environment.
My css.txt file in the clientlib looks like this:
~~~
#base=sass
main.scss
~~~

On hitting _http://localhost:4503/content/mypage.html?debugClientLibs=true_, CSS is not served. On checking the Sources, the CSS file has just one line:
`@import url("/etc/clientlibs/myproject/main/sass/main.scss");`

Please suggest a workaround/fix

**Comment by mickleroy** [comment] 2017-09-21 01:21
Hi @geekyrudh, I'm unable to reproduce your issue when trying with LESS and SASS client libraries with `debugClientLibs=true`. I'm using AEM 6.2 SP1-CFP4.

**Sass:**
http://localhost:4503/etc/designs/helloworld/clientlibs-sass.css?debug=true
```
@import url("/var/clientlibs/etc/designs/helloworld/clientlibs-sass/generated/main.css");
```

**Less:**
http://localhost:4503/etc/designs/helloworld/clientlibs-less.css?debug=true
```
@import url("/var/clientlibs/etc/designs/helloworld/clientlibs-less/generated/main.css");
```

**Foundation CSS:**
http://localhost:4503/etc/clientlibs/foundation/main.css?debug=true
```
@import url("/libs/mcm/components/cta-graphicallink/clientlibs/image.css");
@import url("/libs/foundation/components/textimage/clientlibs/textimage.css");
@import url("/libs/foundation/components/search/clientlibs/search.css");
@import url("/libs/foundation/components/profile/clientlibs/profile.css");
@import url("/libs/foundation/components/parbase/clientlibs/parbase.css");
@import url("/libs/foundation/components/image/clientlibs/image.css");
@import url("/libs/foundation/components/download/clientlibs/download.css");
@import url("/libs/foundation/components/carousel/clientlibs/carousel.css");
@import url("/etc/clientlibs/foundation/form/form.css");
``` 

Naturally, if you are not logged in the "anonymous" user would be used to fetch the compiled CSS under `/var/clientlibs` which would fail.

Is your Sass file compiling?

**Comment by mickleroy** [comment] 2017-09-27 05:14
@geekyrudh have you managed to resolve your issue? If so, I'll close this off.

**Closed as completed** 2017-11-09 12:58 UTC
Labels: question
